# TensorFlow crash course
### **PART 11**

### One-Hot vectors

In [1]:
import tensorflow as tf
vocab = ["<H1 OCEAN", "INLAND", "NEAR OCEAN", "NEAR BAY", "ISLAND"]
indices = tf.range(len(vocab), dtype=tf.int64)
table_init = tf.lookup.KeyValueTensorInitializer(vocab, indices)
num_oov_buckets = 2
table = tf.lookup.StaticVocabularyTable(table_init, num_oov_buckets)

In [2]:
categories = tf.constant(["NEAR OCEAN", "ISLAND"])
cat_indices = table.lookup(categories)  # Convert from categorical to numerical features
print(cat_indices)
cat_one_hot = tf.one_hot(cat_indices, depth=len(vocab) + num_oov_buckets)  # Perform one-hot encoding
print(cat_one_hot)

tf.Tensor([2 4], shape=(2,), dtype=int64)
tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]], shape=(2, 7), dtype=float32)


###  Encoding categorical features using embeddings


In [3]:
embedding_dim = 2
embed_init = tf.random.uniform([len(vocab) + num_oov_buckets, embedding_dim])
embedding_matrix = tf.Variable(embed_init)
print(embedding_matrix)
categories = tf.constant(["NEAR BAY", "DESERT", "INLAND", "INLAND"])
cat_indices = table.lookup(categories)
print(cat_indices)
print(tf.nn.embedding_lookup(embedding_matrix, cat_indices))

<tf.Variable 'Variable:0' shape=(7, 2) dtype=float32, numpy=
array([[0.098189  , 0.1817143 ],
       [0.48924458, 0.00195718],
       [0.76755476, 0.7591735 ],
       [0.93146956, 0.12598276],
       [0.77654743, 0.2661816 ],
       [0.24250579, 0.07413757],
       [0.6545149 , 0.24897623]], dtype=float32)>
tf.Tensor([3 5 1 1], shape=(4,), dtype=int64)
tf.Tensor(
[[0.93146956 0.12598276]
 [0.24250579 0.07413757]
 [0.48924458 0.00195718]
 [0.48924458 0.00195718]], shape=(4, 2), dtype=float32)
