# TensorFlow crash course
### **PART 1**

## Installation on jupyter notebook

In [1]:
!pip install tensorflow

### Import the TensorFlow framework

In [2]:
import tensorflow as tf

### Tensor, matrix and scalar creation using tensorflow

In [3]:
tensor = tf.constant([[[1, 2, 3]], [[4, 5, 6]]])
matrix = tf.constant([[1, 2], [3, 4]])
scalar = tf.constant(1) 
print(tensor, matrix, scalar)

tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]], shape=(2, 1, 3), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(1, shape=(), dtype=int32)


### Get the shape and data type of a particular tensor

In [4]:
#  Shapes
#===============================================|
print(tensor.shape, matrix.shape, scalar.shape)
#===============================================|
#  DataTypes
print(tensor.dtype, matrix.dtype, scalar.dtype)
#===============================================|

(2, 1, 3) (2, 2) ()
<dtype: 'int32'> <dtype: 'int32'> <dtype: 'int32'>


### Transpose of a tensor

In [5]:
print(tf.transpose(tensor))

tf.Tensor(
[[[1 4]]

 [[2 5]]

 [[3 6]]], shape=(3, 1, 2), dtype=int32)


### Sum, Mean, Min, Max

In [6]:
for value, name in zip([tensor, matrix, scalar], ["tensor", "matrix", "scalar"]):
    print(f"{name}")
    print(f"Sum : {tf.reduce_sum(value)}\nMean : {tf.reduce_mean(value)}")
    print(f"Min : {tf.reduce_min(value)}\nMax : {tf.reduce_max(value)}", end="\n|=================|\n")

tensor
Sum : 21
Mean : 3
Min : 1
Max : 6
|=================|
matrix
Sum : 10
Mean : 2
Min : 1
Max : 4
|=================|
scalar
Sum : 1
Mean : 1
Min : 1
Max : 1
|=================|


### Common-Operators
### *1 - Addition*
### *2 - Subtraction*
### *3 - Multiplication*
### *4 - Division*
### *5 - square*
### *6 - sqrt*
#### *Visit [here](https://www.tensorflow.org/api_docs/python/tf/math#functions_2) for more reference.*

In [7]:
for func in [tf.math.add, tf.math.subtract, tf.math.multiply, tf.math.divide, tf.math.square, tf.math.sqrt]:
    if func.__name__ not in ('square', 'sqrt'):
        print(f"{tensor} <{func.__name__}> {tensor} = {func(tensor, tensor)}", end="\n|========================================|\n")
    else:
        #  We'll see tf.cast in the last cell so just know it changes the data type
        print(f"{tensor} <{func.__name__}> = {func(tf.cast(tensor, tf.float16))}", end="\n|========================================|\n")

[[[1 2 3]]

 [[4 5 6]]] <add> [[[1 2 3]]

 [[4 5 6]]] = [[[ 2  4  6]]

 [[ 8 10 12]]]
|========================================|
[[[1 2 3]]

 [[4 5 6]]] <subtract> [[[1 2 3]]

 [[4 5 6]]] = [[[0 0 0]]

 [[0 0 0]]]
|========================================|
[[[1 2 3]]

 [[4 5 6]]] <multiply> [[[1 2 3]]

 [[4 5 6]]] = [[[ 1  4  9]]

 [[16 25 36]]]
|========================================|
[[[1 2 3]]

 [[4 5 6]]] <divide> [[[1 2 3]]

 [[4 5 6]]] = [[[1. 1. 1.]]

 [[1. 1. 1.]]]
|========================================|
[[[1 2 3]]

 [[4 5 6]]] <square> = [[[ 1.  4.  9.]]

 [[16. 25. 36.]]]
|========================================|
[[[1 2 3]]

 [[4 5 6]]] <sqrt> = [[[1.    1.414 1.732]]

 [[2.    2.236 2.45 ]]]
|========================================|


### NumPy Conversion

In [8]:
for value, name in zip([tensor, matrix, scalar], ["tensor", "matrix", "scalar"]):
    print(f"NumPy form of {name} : {value.numpy()}", end="\n|=================|\n")

NumPy form of tensor : [[[1 2 3]]

 [[4 5 6]]]
|=================|
NumPy form of matrix : [[1 2]
 [3 4]]
|=================|
NumPy form of scalar : 1
|=================|


### Type Conversions

In [9]:
tensor1 = tf.constant([[[1, 2]], [[3, 4]]], dtype=tf.float32)
tensor2 = tf.constant([[[5, 6]], [[7, 8]]], dtype=tf.int32)
#  Don't attempt to perform operations of two various data types otherwise you're gonna face errors
#  Change the data type
new_tensor2 = tf.cast(tensor2, tf.float32)
print(tensor1 + new_tensor2)

tf.Tensor(
[[[ 6.  8.]]

 [[10. 12.]]], shape=(2, 1, 2), dtype=float32)
